-- =============================================================================
-- P20X · mensagem do dia
--
-- Uma para cada dia do ano, com versículo e uma frase que liga o texto ao
-- treino. O versículo vem da tradução João Ferreira de Almeida, que é de
-- domínio público, buscado de `bible-api.com` por `scripts/mensagens.mjs` —
-- citar de memória seria o jeito mais fácil de errar.
--
-- A escolha do dia é determinística: todo mundo vê a mesma mensagem no mesmo
-- dia, o que faz dela assunto em comum. E como mora no banco, não depende de
-- nenhuma API de terceiros estar no ar.
--
-- Gerado. Para refazer: `node scripts/mensagens.mjs`.
-- =============================================================================

create table if not exists public.daily_messages (
  day_of_year smallint primary key check (day_of_year between 1 and 366),
  reference   text not null,
  verse       text not null,
  theme       text not null,
  message     text not null
);

alter table public.daily_messages enable row level security;

-- leitura livre: a mensagem do dia também aparece para quem ainda não entrou
create policy "mensagem do dia leitura" on public.daily_messages
  for select to anon, authenticated using (true);

insert into public.daily_messages (day_of_year, reference, verse, theme, message) values
  (1, 'Filipenses 4:13', 'Posso todas as coisas naquele que me fortalece.', 'constancia', 'Hoje é dia 1 de alguma coisa. Não precisa ser bonito, precisa ser feito.'),
  (2, 'Provérbios 13:4', 'O preguiçoso deseja, e coisa nenhuma alcança; mas o desejo do diligente será satisfeito.', 'disciplina', 'Querer é o começo. Levantar e ir é o que separa quem quer de quem faz.'),
  (3, 'Eclesiastes 9:10', 'Tudo quanto te vier à mão para fazer, faze-o conforme as tuas forças; porque no Seol, para onde tu vais, não há obra, nem projeto, nem conhecimento, nem sabedoria alguma.', 'esforco', 'O que você tem para dar hoje é o suficiente. Dê inteiro.'),
  (4, 'Isaías 40:31', 'mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias; correrão, e não se cansarão; andarão, e não se fatigarão.', 'resistencia', 'Cansaço faz parte. Ele passa antes do resultado ir embora.'),
  (5, 'Gálatas 6:9', 'E não nos cansemos de fazer o bem, porque a seu tempo ceifaremos, se não houvermos desfalecido.', 'constancia', 'Ninguém colhe no mesmo dia em que planta. Continue plantando.'),
  (6, 'Josué 1:9', 'Não to mandei eu? Esforça-te, e tem bom ânimo; não te atemorizes, nem te espantes; porque o Senhor teu Deus está contigo, por onde quer que andares.', 'coragem', 'A parte difícil não é o treino. É a decisão que vem dez minutos antes.'),
  (7, 'Salmos 37:5', 'Entrega o teu caminho ao Senhor; confia nele, e ele tudo fará.', 'proposito', 'Você não precisa enxergar o fim para dar o próximo passo.'),
  (8, 'Provérbios 21:5', 'Os planos do diligente conduzem à abundância; mas todo precipitado apressa-se para a penúria.', 'paciencia', 'Pressa cansa. Método chega.'),
  (9, '1 Coríntios 9:24', 'Não sabeis vós que os que correm no estádio, todos, na verdade, correm, mas um só é que recebe o prêmio? Correi de tal maneira que o alcanceis.', 'foco', 'Corra como quem quer chegar, não como quem quer parecer que corre.'),
  (10, 'Tiago 1:12', 'Bem-aventurado o homem que suporta a provação; porque, depois de aprovado, receberá a coroa da vida, que o Senhor prometeu aos que o amam.', 'perseveranca', 'O que te testa hoje é o que te sustenta depois.'),
  (11, 'Salmos 18:32', 'Ele é o Deus que me cinge de força e torna perfeito o meu caminho;', 'forca', 'A força que você procura já está sendo construída — em silêncio.'),
  (12, 'Provérbios 24:16', 'Porque sete vezes cai o justo, e se levanta; mas os ímpios são derribados pela calamidade.', 'recomeco', 'Cair não desfaz o caminho. Ficar caído, sim.'),
  (13, 'Colossenses 3:23', 'E tudo quanto fizerdes, fazei-o de coração, como ao Senhor, e não aos homens,', 'excelencia', 'Faça como quem tem para quem prestar contas. Porque tem: você.'),
  (14, 'Hebreus 12:1', 'Portanto, nós também, pois estamos rodeados de tão grande nuvem de testemunhas, deixemos todo embaraço, e o pecado que tão de perto nos rodeia, e corramos com perseverança a carreira que nos está proposta,', 'leveza', 'Solte o que pesa e não te leva a lugar nenhum.'),
  (15, 'Salmos 121:1', 'Elevo os meus olhos para os montes; de onde me vem o socorro?', 'esperanca', 'Levante a cabeça. O dia ainda tem 20 minutos para você.'),
  (16, 'Provérbios 16:3', 'Entrega ao Senhor as tuas obras, e teus desígnios serão estabelecidos.', 'planejamento', 'Decida agora quando vai treinar. Depois é só cumprir.'),
  (17, '2 Timóteo 1:7', 'Porque Deus não nos deu o espírito de covardia, mas de poder, de amor e de moderação.', 'coragem', 'Medo de não dar conta some depois do primeiro round.'),
  (18, 'Salmos 23:1', 'O Senhor é o meu pastor; nada me faltará.', 'confianca', 'Você tem o que precisa. Falta usar.'),
  (19, 'Mateus 7:24', 'Todo aquele, pois, que ouve estas minhas palavras e as põe em prática, será comparado a um homem prudente, que edificou a casa sobre a rocha.', 'fundamento', 'Rotina é a rocha. Motivação é a areia.'),
  (20, 'Romanos 5:3', 'E não somente isso, mas também gloriemo-nos nas tribulações; sabendo que a tribulação produz a perseverança,', 'perseveranca', 'A dificuldade de hoje está te ensinando a aguentar a de amanhã.'),
  (21, 'Provérbios 27:17', 'Afia-se o ferro com o ferro; assim o homem afia o rosto do seu amigo.', 'comunidade', 'Treinar sozinho funciona. Treinar acompanhado dura mais.'),
  (22, 'Isaías 41:10', 'não temas, porque eu sou contigo; não te assombres, porque eu sou teu Deus; eu te fortaleço, e te ajudo, e te sustento com a destra da minha justiça.', 'coragem', 'Não é sobre não sentir medo. É sobre começar mesmo assim.'),
  (23, 'Salmos 119:105', 'Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.', 'clareza', 'Você não precisa ver o mês inteiro. Só o próximo passo.'),
  (24, '1 Coríntios 15:58', 'Portanto, meus amados irmãos, sede firmes e constantes, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor.', 'constancia', 'Nenhum treino registrado é desperdiçado. Nenhum.'),
  (25, 'Provérbios 12:24', 'A mão dos diligentes dominará; mas o indolente será tributário servil.', 'disciplina', 'Quem manda no seu dia é quem decide o seu corpo.'),
  (26, 'Filipenses 3:14', 'prossigo para o alvo pelo prêmio da vocação celestial de Deus em Cristo Jesus.', 'foco', 'Não olhe para trás para se cobrar. Olhe para frente para continuar.'),
  (27, 'Salmos 46:1', 'Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.', 'resiliencia', 'Dia ruim não cancela o compromisso. Só muda o tamanho dele.'),
  (28, 'Eclesiastes 3:1', 'Tudo tem a sua ocasião própria, e há tempo para todo propósito debaixo do céu.', 'paciencia', 'Tem tempo para forçar e tempo para descansar. Saiba qual é hoje.'),
  (29, 'Marcos 9:23', 'Ao que lhe disse Jesus: Se podes! - tudo é possível ao que crê.', 'fe', 'O corpo obedece ao que a cabeça acredita ser possível.'),
  (30, 'Provérbios 4:25', 'Dirijam-se os teus olhos para a frente, e olhem as tuas pálpebras diretamente diante de ti.', 'foco', 'Olhe para o que está fazendo agora. O resto espera.'),
  (31, 'Salmos 27:14', 'Espera tu pelo Senhor; anima-te, e fortalece o teu coração; espera, pois, pelo Senhor.', 'paciencia', 'Resultado atrasa, mas não falta a quem insiste.'),
  (32, '2 Coríntios 4:16', 'Por isso não desfalecemos; mas ainda que o nosso homem exterior se esteja consumindo, o interior, contudo, se renova de dia em dia.', 'renovacao', 'O corpo cansa por fora e se refaz por dentro. Todo dia.'),
  (33, 'Neemias 6:3', 'E enviei-lhes mensageiros a dizer: Estou fazendo uma grande obra, de modo que não poderei descer. Por que cessaria esta obra, enquanto eu a deixasse e fosse ter convosco?', 'prioridade', 'Você está fazendo uma coisa grande. Não desça para o que te distrai.'),
  (34, 'Provérbios 20:4', 'O preguiçoso não lavra no outono; pelo que mendigará na sega, e nada receberá.', 'disciplina', 'A desculpa de hoje é a falta de amanhã.'),
  (35, 'Salmos 91:1', 'Aquele que habita no esconderijo do Altíssimo, à sombra do Todo-Poderoso descansará.', 'seguranca', 'Vinte minutos por dia são seu abrigo contra o resto.'),
  (36, 'Lucas 16:10', 'Quem é fiel no pouco, também é fiel no muito; quem é injusto no pouco, também é injusto no muito.', 'constancia', 'Quem é fiel no treino curto é fiel no longo.'),
  (37, 'Isaías 43:19', 'Eis que faço uma coisa nova; agora está saindo à luz; porventura não a percebeis? eis que porei um caminho no deserto, e rios no ermo.', 'recomeco', 'Não importa quantas vezes você já parou. Importa hoje.'),
  (38, 'Tiago 2:17', 'Assim também a fé, se não tiver obras, é morta em si mesma.', 'acao', 'Intenção sem movimento não move nada.'),
  (39, 'Salmos 139:14', 'Eu te louvarei, porque de um modo tão admirável e maravilhoso fui formado; maravilhosas são as tuas obras, e a minha alma o sabe muito bem.', 'gratidao', 'Esse corpo aguenta mais do que você imagina. Trate-o assim.'),
  (40, 'Provérbios 15:22', 'Onde não há conselho, frustram-se os projetos; mas com a multidão de conselheiros se estabelecem.', 'planejamento', 'Escolha o treino antes de ter que decidir cansado.'),
  (41, '1 Pedro 5:7', 'lançando sobre ele toda a vossa ansiedade, porque ele tem cuidado de vós.', 'leveza', 'Deixe o dia ruim do lado de fora. Aqui é só você e o relógio.'),
  (42, 'Efésios 6:10', 'Finalmente, fortalecei-vos no Senhor e na força do seu poder.', 'forca', 'Comece forte. Se não der, comece devagar — mas comece.'),
  (43, 'Salmos 84:7', 'Vão sempre aumentando de força; cada um deles aparece perante Deus em Sião.', 'progresso', 'De força em força. É assim que se anda longe.'),
  (44, 'Provérbios 3:5', 'Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.', 'confianca', 'Confie no processo mesmo nos dias em que ele não parece funcionar.'),
  (45, 'Hebreus 10:36', 'Porque necessitais de perseverança, para que, depois de haverdes feito a vontade de Deus, alcanceis a promessa.', 'perseveranca', 'Falta paciência, não capacidade.'),
  (46, 'Mateus 6:34', 'Não vos inquieteis, pois, pelo dia de amanhã; porque o dia de amanhã cuidará de si mesmo. Basta a cada dia o seu mal.', 'presente', 'Não carregue a semana inteira agora. Só hoje.'),
  (47, 'Salmos 30:5', 'Porque a sua ira dura só um momento; no seu favor está a vida. O choro pode durar uma noite; pela manhã, porém, vem o cântico de júbilo.', 'esperanca', 'Todo cansaço tem hora de acabar. Chegue lá.'),
  (48, 'Provérbios 11:25', 'A alma generosa prosperará, e o que regar também será regado.', 'generosidade', 'Chame alguém para treinar. Você ganha junto.'),
  (49, 'Gálatas 5:1', 'Para a liberdade Cristo nos libertou; permanecei, pois, firmes e não vos dobreis novamente a um jogo de escravidão.', 'liberdade', 'Você escolheu isso. Ninguém te obrigou. Isso muda tudo.'),
  (50, 'Salmos 34:8', 'Provai, e vede que o Senhor é bom; bem-aventurado o homem que nele se refugia.', 'experiencia', 'Prove um dia bom de treino e você entende por que insistimos.'),
  (51, '1 Timóteo 4:8', 'Pois o exercício corporal para pouco aproveita, mas a piedade para tudo é proveitosa, visto que tem a promessa da vida presente e da que há de vir.', 'corpo', 'Cuidar do corpo é útil. Cuidar da constância é mais.'),
  (52, 'Provérbios 6:6', 'Vai ter com a formiga, ó preguiçoso, considera os seus caminhos, e sê sábio;', 'disciplina', 'Ninguém precisa mandar a formiga trabalhar. Nem você.'),
  (53, 'Isaías 40:29', 'Ele dá força ao cansado, e aumenta as forças ao que não tem nenhum vigor.', 'forca', 'Justamente quando não sobra força é que ela é dada.'),
  (54, 'Salmos 62:1', 'Somente em Deus espera silenciosa a minha alma; dele vem a minha salvação.', 'calma', 'Respire. Vinte minutos não são uma guerra.'),
  (55, 'Romanos 12:2', 'E não vos conformeis a este mundo, mas transformai-vos pela renovação da vossa mente, para que experimenteis qual seja a boa, agradável, e perfeita vontade de Deus.', 'mudanca', 'Mude a rotina e o corpo muda atrás.'),
  (56, 'Provérbios 25:28', 'Como a cidade derribada, que não tem muros, assim é o homem que não pode conter o seu espírito.', 'dominio', 'Domínio de si é a força que ninguém vê no espelho.'),
  (57, 'Filipenses 1:6', 'tendo por certo isto mesmo, que aquele que em vós começou a boa obra a aperfeiçoará até o dia de Cristo Jesus,', 'confianca', 'O que começou em você não vai parar pela metade.'),
  (58, 'Salmos 118:24', 'Este é o dia que o Senhor fez; regozijemo-nos, e alegremo-nos nele.', 'gratidao', 'Hoje é o único dia em que você pode treinar hoje.'),
  (59, 'Eclesiastes 4:9', 'Melhor é serem dois do que um, porque têm melhor paga do seu trabalho.', 'comunidade', 'Dois rendem mais que um. Vale para treino também.'),
  (60, '2 Crônicas 15:7', 'Vós, porém, esforçai-vos, e não desfaleçam as vossas mãos; porque a vossa obra terá uma recompensa.', 'esforco', 'Seu trabalho tem recompensa. Não afrouxe as mãos.'),
  (61, 'Provérbios 14:23', 'Em todo trabalho há proveito; meras palavras, porém, só encaminham para a penúria.', 'acao', 'Conversa sobre treino não queima caloria nenhuma.'),
  (62, 'Salmos 51:10', 'Cria em mim, ó Deus, um coração puro, e renova em mim um espírito estável.', 'recomeco', 'Coração renovado, semana renovada. Comece de novo, sem culpa.'),
  (63, 'Mateus 11:28', 'Vinde a mim, todos os que estai cansados e oprimidos, e eu vos aliviarei.', 'descanso', 'Descansar é parte do plano, não fuga dele.'),
  (64, 'Provérbios 22:29', 'Vês um homem hábil na sua obrar? esse perante reis assistirá; e não assistirá perante homens obscuros.', 'excelencia', 'Faça bem feito o simples. É o simples que te leva longe.'),
  (65, 'Isaías 26:3', 'Tu conservarás em paz aquele cuja mente está firme em ti; porque ele confia em ti.', 'paz', 'Mente firme faz corpo firme.'),
  (66, 'Salmos 16:8', 'Tenho posto o Senhor continuamente diante de mim; porquanto ele está à minha mão direita, não serei abalado.', 'firmeza', 'Não vou vacilar hoje. Só hoje. Amanhã eu decido de novo.'),
  (67, '1 Coríntios 10:31', 'Portanto, quer comais quer bebais, ou façais, qualquer outra coisa, fazei tudo para glória de Deus.', 'proposito', 'Até o treino tem sentido quando você sabe por que faz.'),
  (68, 'Provérbios 28:1', 'Fogem os ímpios, sem que ninguém os persiga; mas os justos são ousados como o leão.', 'coragem', 'Ande como quem confia no próprio esforço.'),
  (69, 'Jeremias 29:11', 'Pois eu bem sei os planos que estou projetando para vós, diz o Senhor; planos de paz, e não de mal, para vos dar um futuro e uma esperança.', 'esperanca', 'Existe um plano para você que não termina hoje.'),
  (70, 'Salmos 145:14', 'O Senhor sustém a todos os que estão a cair, e levanta a todos os que estão abatidos.', 'recomeco', 'Quem cai é levantado. Levante.'),
  (71, 'Lucas 14:28', 'Pois qual de vós, querendo edificar uma torre, não se senta primeiro a calcular as despesas, para ver se tem com que a acabar?', 'planejamento', 'Calcule o custo e pague. Vinte minutos é barato.'),
  (72, 'Efésios 4:22', 'a despojar-vos, quanto ao procedimento anterior, do velho homem, que se corrompe pelas concupiscências do engano;', 'mudanca', 'Deixe para trás quem você era às seis da tarde de ontem.'),
  (73, 'Provérbios 10:4', 'O que trabalha com mão remissa empobrece; mas a mão do diligente enriquece.', 'esforco', 'Mão preguiçosa empobrece. Mão diligente enriquece. Vale para saúde.'),
  (74, 'Salmos 40:1', 'Esperei com paciência pelo Senhor, e ele se inclinou para mim e ouviu o meu clamor.', 'paciencia', 'Esperar com paciência não é ficar parado.'),
  (75, 'Hebreus 11:1', 'Ora, a fé é o firme fundamento das coisas que se esperam, e a prova das coisas que não se vêem.', 'fe', 'Você ainda não vê o resultado. Ele já está sendo feito.'),
  (76, 'Provérbios 18:9', 'Aquele que é remisso na sua obra é irmão do que é destruidor.', 'disciplina', 'Relaxar no trabalho é irmão de destruir o que se construiu.'),
  (77, 'Salmos 103:5', 'quem te supre de todo o bem, de sorte que a tua mocidade se renova como a da águia.', 'renovacao', 'A juventude se renova em quem se move.'),
  (78, '2 Timóteo 4:7', 'Combati o bom combate, acabei a carreira, guardei a fé.', 'perseveranca', 'Combater o bom combate é chegar ao fim, não vencer todo dia.'),
  (79, 'Isaías 54:2', 'Amplia o lugar da tua tenda, e estendam-se as cortinas das tuas habitações; não o impeças; alonga as tuas cordas, e firma bem as tuas estacas.', 'crescimento', 'Alargue o espaço. Você aguenta mais do que aguentava.'),
  (80, 'Provérbios 16:9', 'O coração do homem propõe o seu caminho; mas o Senhor lhe dirige os passos.', 'flexibilidade', 'Planeje o dia e aceite que ele mude. Só não pule o treino.'),
  (81, 'Salmos 143:8', 'Faze-me ouvir da tua benignidade pela manhã, pois em ti confio; faze-me saber o caminho que devo seguir, porque a ti elevo a minha alma.', 'manha', 'Comece cedo. O dia não vai te dar tempo depois.'),
  (82, 'Tiago 4:17', 'Aquele, pois, que sabe fazer o bem e não o faz, comete pecado.', 'acao', 'Você sabe o que fazer. Falta fazer.'),
  (83, 'Colossenses 3:2', 'Pensai nas coisas que são de cima, e não nas que são da terra;', 'foco', 'Pense no que você quer ser daqui a um ano. Depois treine.'),
  (84, 'Provérbios 31:17', 'Hete. Cinge os seus lombos de força, e fortalece os seus braços.', 'forca', 'Cinja-se de força. Fortaleça os braços. Literalmente.'),
  (85, 'Salmos 20:4', 'Conceda-te conforme o desejo do teu coração, e cumpra todo o teu desígnio.', 'proposito', 'Que o seu objetivo se cumpra. Comece por hoje.'),
  (86, '1 João 5:4', 'porque todo o que é nascido de Deus vence o mundo; e esta é a vitória que vence o mundo: a nossa fé.', 'vitoria', 'O que vence o cansaço é a decisão tomada antes dele.'),
  (87, 'Provérbios 19:21', 'Muitos são os planos no coração do homem; mas o desígnio do Senhor, esse prevalecerá.', 'humildade', 'Muitos planos, um caminho. Ande o de hoje.'),
  (88, 'Isaías 30:15', 'Pois assim diz o Senhor Deus, o Santo de Israel: Voltando e descansando, sereis salvos; no sossego e na confiança estará a vossa força. Mas não quisestes;', 'calma', 'Na quietude e na confiança está a sua força.'),
  (89, 'Salmos 3:5', 'Eu me deito e durmo; acordo, pois o Senhor me sustenta.', 'descanso', 'Dormiu, acordou, está de pé. Já tem com o que trabalhar.'),
  (90, 'Mateus 25:21', 'Disse-lhe o seu senhor: Muito bem, servo bom e fiel; sobre o pouco foste fiel, sobre muito te colocarei; entra no gozo do teu senhor.', 'constancia', 'Fiel no pouco. É assim que se chega ao muito.'),
  (91, 'Provérbios 4:23', 'Guarda com toda a diligência o teu coração, porque dele procedem as fontes da vida.', 'dominio', 'Guarde o coração e a rotina se guarda sozinha.'),
  (92, 'Salmos 73:26', 'A minha carne e o meu coração desfalecem; do meu coração, porém, Deus é a fortaleza, e o meu quinhão para sempre.', 'forca', 'A carne falha. A decisão não precisa falhar junto.'),
  (93, 'Provérbios 27:1', 'Não te glories do dia de amanhã; porque não sabes o que produzirá o dia.', 'presente', 'Não prometa amanhã o que cabe em vinte minutos hoje.'),
  (94, 'Salmos 55:22', 'Lança o teu fardo sobre o Senhor, e ele te susterá; nunca permitirá que o justo seja abalado.', 'leveza', 'Entregue o peso que não é seu e carregue só a barra.'),
  (95, 'Isaías 58:11', 'O Senhor te guiará continuamente, e te fartará até em lugares áridos, e fortificará os teus ossos; serás como um jardim regado, e como um manancial, cujas águas nunca falham.', 'renovacao', 'Você vai ser como um jardim regado. Regue todo dia.'),
  (96, '1 Coríntios 6:19', 'Ou não sabeis que o vosso corpo é santuário do Espírito Santo, que habita em vós, o qual possuís da parte de Deus, e que não sois de vós mesmos?', 'corpo', 'Esse corpo é templo. Templo se cuida, não se abandona.'),
  (97, 'Provérbios 15:19', 'O caminho do preguiçoso é como a sebe de espinhos; porém a vereda dos justos é uma estrada real.', 'disciplina', 'O caminho do preguiçoso é cheio de espinhos. O do reto é plano.'),
  (98, 'Salmos 42:11', 'Por que estás abatida, ó minha alma, e por que te perturbas dentro de mim? Espera em Deus, pois ainda o louvarei, a ele que é o meu socorro, e o meu Deus.', 'animo', 'Por que estás abatida, alma minha? Levanta e treina.'),
  (99, 'Hebreus 12:11', 'Na verdade, nenhuma correção parece no momento ser motivo de gozo, porém de tristeza; mas depois produz um fruto pacífico de justiça nos que por ele têm sido exercitados.', 'dor', 'Nenhuma disciplina parece boa na hora. Depois, dá fruto.'),
  (100, 'Mateus 5:6', 'Bem-aventurados os que têm fome e sede de justiça porque eles serão fartos.', 'fome', 'Tenha fome do que você quer ser. Ela é que sustenta a rotina.'),
  (101, 'Provérbios 24:10', 'Se enfraqueces no dia da angústia, a tua força é pequena.', 'resiliencia', 'Se você desanima no dia da angústia, a força era pequena. Aumente.'),
  (102, 'Salmos 31:24', 'Esforçai-vos, e fortaleça-se o vosso coração, vós todos os que esperais no Senhor.', 'coragem', 'Esforce-se e ele fortalecerá o seu coração.'),
  (103, 'Eclesiastes 11:4', 'Quem observa o vento, não semeará, e o que atenta para as nuvens não segará.', 'acao', 'Quem espera o vento perfeito nunca semeia. Treine no vento que tem.'),
  (104, 'Romanos 8:37', 'Mas em todas estas coisas somos mais que vencedores, por aquele que nos amou.', 'vitoria', 'Mais que vencedor. Inclusive do sofá.'),
  (105, 'Provérbios 3:8', 'Isso será saúde para a tua carne; e refrigério para os teus ossos.', 'saude', 'Isso será saúde para o seu corpo e refrigério para os seus ossos.'),
  (106, 'Salmos 5:3', 'Pela manhã ouves a minha voz, ó Senhor; pela manhã te apresento a minha oração, e vigio.', 'manha', 'De manhã ouvirás a minha voz. E o meu treino.'),
  (107, 'Tiago 1:22', 'E sede cumpridores da palavra e não somente ouvintes, enganando-vos a vós mesmos.', 'acao', 'Ser ouvinte da própria promessa não muda ninguém.'),
  (108, 'Isaías 55:11', 'assim será a palavra que sair da minha boca: ela não voltará para mim vazia, antes fará o que me apraz, e prosperará naquilo para que a enviei.', 'constancia', 'O que sai de você não volta vazio. Continue.'),
  (109, 'Provérbios 21:31', 'O cavalo prepara-se para o dia da batalha; mas do Senhor vem a vitória.', 'preparo', 'Prepare o cavalo para o dia da batalha. Prepare o corpo para a vida.'),
  (110, 'Salmos 138:3', 'No dia em que eu clamei, atendeste-me; alentaste-me, fortalecendo a minha alma.', 'forca', 'No dia em que clamei, me fortaleceste com força na minha alma.'),
  (111, 'Lucas 9:23', 'Em seguida dizia a todos: Se alguém quer vir após mim, negue-se a si mesmo, tome cada dia a sua cruz, e siga-me.', 'diario', 'Cada dia. Não cada semana, não quando der. Cada dia.'),
  (112, 'Provérbios 12:1', 'O que ama a correção ama o conhecimento; mas o que aborrece a repreensão é insensato.', 'humildade', 'Quem aceita correção aprende. Quem se justifica repete.'),
  (113, 'Salmos 92:14', 'Na velhice ainda darão frutos, serão viçosos e florescentes,', 'longevidade', 'Na velhice ainda darão frutos. Comece a plantar agora.'),
  (114, '1 Coríntios 9:27', 'Antes subjugo o meu corpo, e o reduzo à submissão, para que, depois de pregar a outros, eu mesmo não venha a ficar reprovado.', 'dominio', 'Eu subjugo o meu corpo. Ele não manda em mim.'),
  (115, 'Jeremias 17:8', 'Porque é como a árvore plantada junto às águas, que estende as suas raízes para o ribeiro, e não receia quando vem o calor, mas a sua folha fica verde; e no ano de sequidão não se afadiga, nem deixa de dar fruto.', 'raiz', 'Raiz funda não teme o calor. Rotina funda não teme a semana ruim.'),
  (116, 'Provérbios 13:11', 'A riqueza adquirida às pressas diminuira; mas quem a ajunta pouco a pouco terá aumento.', 'paciencia', 'O que vem pouco a pouco aumenta. O que vem rápido some.'),
  (117, 'Salmos 37:23', 'Confirmados pelo Senhor são os passos do homem em cujo caminho ele se deleita;', 'caminho', 'Passo firme não é passo rápido.'),
  (118, 'Mateus 26:41', 'Vigiai e orai, para que não entreis em tentação; o espírito, na verdade, está pronto, mas a carne é fraca.', 'vontade', 'O espírito está pronto, a carne é fraca. Comece antes de negociar.'),
  (119, 'Efésios 5:16', 'usando bem cada oportunidade, porquanto os dias são maus.', 'tempo', 'Aproveite bem o tempo. Ele não volta.'),
  (120, 'Provérbios 17:22', 'O coração alegre serve de bom remédio; mas o espírito abatido seca os ossos.', 'animo', 'Coração alegre é bom remédio. Treino também.'),
  (121, 'Salmos 40:2', 'Também me tirou duma cova de destruição, dum charco de lodo; pôs os meus pés sobre uma rocha, firmou os meus passos.', 'recomeco', 'Tirou os pés do lodo e firmou sobre a rocha. É o que a rotina faz.'),
  (122, 'Isaías 35:3', 'Fortalecei as mãos fracas, e firmai os joelhos trementes.', 'forca', 'Fortaleça as mãos frouxas e firme os joelhos vacilantes.'),
  (123, 'Gálatas 6:4', 'Mas prove cada um a sua própria obra, e então terá motivo de glória somente em si mesmo, e não em outrem;', 'comparacao', 'Prove a sua própria obra. Não a de ninguém.'),
  (124, 'Provérbios 14:30', 'O coração tranqüilo é a vida da carne; a inveja, porém, é a podridão dos ossos.', 'paz', 'Inveja apodrece os ossos. Olhe para o seu próprio caminho.'),
  (125, 'Salmos 119:32', 'Percorrerei o caminho dos teus mandamentos, quando dilatares o meu coração.', 'liberdade', 'Correrei quando dilatares o meu coração.'),
  (126, 'Filipenses 4:6', 'Não andeis ansiosos por coisa alguma; antes em tudo sejam os vossos pedidos conhecidos diante de Deus pela oração e súplica com ações de graças;', 'ansiedade', 'Ansioso por nada. Vinte minutos resolvem mais do que parece.'),
  (127, '1 Tessalonicenses 5:17', 'Orai sem cessar.', 'constancia', 'Sem cessar. É essa a palavra.'),
  (128, 'Provérbios 30:25', 'as formigas são um povo sem força, todavia no verão preparam a sua comida;', 'preparo', 'As formigas preparam no verão a comida do inverno.'),
  (129, 'Salmos 63:1', 'Ó Deus, tu és o meu Deus; ansiosamente te busco. A minha alma tem sede de ti; a minha carne te deseja muito em uma terra seca e cansada, onde não há água.', 'sede', 'Minha alma tem sede. Beba água também.'),
  (130, 'Hebreus 6:12', 'para que não vos torneis indolentes, mas sejais imitadores dos que pela fé e paciência herdam as promessas.', 'perseveranca', 'Não sejam preguiçosos: imitem os que pela fé e paciência herdam.'),
  (131, 'Isaías 61:3', 'a ordenar acerca dos que choram em Sião que se lhes dê uma grinalda em vez de cinzas, óleo de gozo em vez de pranto, vestidos de louvor em vez de espírito angustiado; a fim de que se chamem árvores de justiça, plantação do Senhor, para que ele seja glorificado.', 'troca', 'Óleo de alegria em vez de tristeza. Movimento em vez de peso.'),
  (132, 'Provérbios 23:12', 'Aplica o teu coração à instrução, e os teus ouvidos às palavras do conhecimento.', 'aprendizado', 'Aplique o coração ao ensino. Inclusive ao do próprio corpo.'),
  (133, 'Salmos 147:3', 'sara os quebrantados de coração, e cura-lhes as feridas;', 'cura', 'Sara os quebrantados e liga as suas feridas. Dê tempo ao corpo.'),
  (134, 'Marcos 1:35', 'De madrugada, ainda bem escuro, levantou-se, saiu e foi a um lugar deserto, e ali orava.', 'manha', 'De madrugada, muito cedo, foi para um lugar deserto. E orou.'),
  (135, 'Provérbios 11:2', 'Quando vem a soberba, então vem a desonra; mas com os humildes está a sabedoria.', 'humildade', 'Com os humildes está a sabedoria. Comece leve, cresça sempre.'),
  (136, 'Salmos 112:7', 'Ele não teme más notícias; o seu coração está firme, confiando no Senhor.', 'firmeza', 'Coração firme não teme más notícias. Nem segunda-feira.'),
  (137, '2 Coríntios 12:9', 'e ele me disse: A minha graça te basta, porque o meu poder se aperfeiçoa na fraqueza. Por isso, de boa vontade antes me gloriarei nas minhas fraquezas, a fim de que repouse sobre mim o poder de Cristo.', 'fraqueza', 'Na fraqueza é que a força aparece inteira.'),
  (138, 'Provérbios 16:32', 'Melhor é o longânimo do que o valente; e o que domina o seu espírito do que o que toma uma cidade.', 'dominio', 'Melhor o que domina o seu ânimo do que o que toma uma cidade.'),
  (139, 'Salmos 90:12', 'Ensina-nos a contar os nossos dias de tal maneira que alcancemos corações sábios.', 'tempo', 'Ensina-nos a contar os nossos dias. Sessenta e cinco por ano, se você quiser.'),
  (140, 'João 16:33', 'Tenho-vos dito estas coisas, para que em mim tenhais paz. No mundo tereis tribulações; mas tende bom ânimo, eu venci o mundo.', 'resiliencia', 'No mundo tereis aflições. Tende bom ânimo.'),
  (141, 'Provérbios 9:9', 'Instrui ao sábio, e ele se fará mais, sábio; ensina ao justo, e ele crescerá em entendimento.', 'aprendizado', 'Ensine ao sábio e ele será mais sábio. Ajuste o treino e ele rende mais.'),
  (142, 'Salmos 32:8', 'Instruir-te-ei, e ensinar-te-ei o caminho que deves seguir; aconselhar-te-ei, tendo-te sob a minha vista.', 'direcao', 'Eu te instruirei e te ensinarei o caminho. Um passo por vez.'),
  (143, 'Isaías 48:17', 'Assim diz o Senhor, o teu Redentor, o Santo de Israel: Eu sou o Senhor, o teu Deus, que te ensina o que é útil, e te guia pelo caminho em que deves andar.', 'direcao', 'Eu te ensino o que é útil e te guio pelo caminho.'),
  (144, 'Provérbios 29:23', 'A soberba do homem o abaterá; mas o humilde de espírito obterá honra.', 'humildade', 'A soberba abate. A humildade sustenta.'),
  (145, 'Salmos 66:12', 'Fizeste com que os homens cavalgassem sobre as nossas cabeças; passamos pelo fogo e pela água, mas nos trouxeste a um lugar de abundância.', 'travessia', 'Passamos pelo fogo e pela água, e nos trouxeste a um lugar largo.'),
  (146, 'Tiago 5:11', 'Eis que chamamos bem-aventurados os que suportaram aflições. Ouvistes da paciência de Jó, e vistes o fim que o Senhor lhe deu, porque o Senhor é cheio de misericórdia e compaixão.', 'perseveranca', 'Bem-aventurados os que perseveram.'),
  (147, 'Provérbios 8:34', 'Feliz é o homem que me dá ouvidos, velando cada dia às minhas entradas, esperando junto às ombreiras da minha porta.', 'rotina', 'Bem-aventurado quem vela todos os dias às minhas portas.'),
  (148, 'Salmos 71:16', 'Virei na força do Senhor Deus; farei menção da tua justiça, da tua tão somente.', 'forca', 'Irei na força do Senhor. Não na minha vontade do dia.'),
  (149, 'Eclesiastes 7:8', 'Melhor é o fim duma coisa do que o princípio; melhor é o paciente do que o arrogante.', 'final', 'Melhor o fim das coisas do que o princípio. Termine.'),
  (150, 'Colossenses 1:11', 'corroborados com toda a fortaleza, segundo o poder da sua glória, para toda a perseverança e longanimidade com gozo;', 'paciencia', 'Fortalecidos para toda a paciência e longanimidade, com gozo.'),
  (151, 'Provérbios 2:11', 'o bom siso te protegerá, e o discernimento e guardará;', 'prudencia', 'O bom senso te guarda. Não force o que está doendo.'),
  (152, 'Salmos 61:2', 'Desde a extremidade da terra clamo a ti, estando abatido o meu coração; leva-me para a rocha que é mais alta do que eu.', 'socorro', 'Do fim da terra clamo. Leve-me à rocha mais alta que eu.'),
  (153, 'Isaías 43:2', 'Quando passares pelas águas, eu serei contigo; quando pelos rios, eles não te submergirão; quando passares pelo fogo, não te queimarás, nem a chama arderá em ti.', 'travessia', 'Quando passares pelas águas, estarei contigo.'),
  (154, 'Provérbios 15:1', 'A resposta branda desvia o furor, mas a palavra dura suscita a ira.', 'calma', 'Resposta branda desvia o furor. Serve para o seu diálogo interno também.'),
  (155, 'Salmos 100:2', 'Servi ao Senhor com alegria, e apresentai-vos a ele com cântico.', 'alegria', 'Servi com alegria. Treine com alegria.'),
  (156, 'Romanos 15:1', 'Ora nós, que somos fortes, devemos suportar as fraquezas dos fracos, e nào agradar a nós mesmos.', 'servico', 'Os fortes suportam as fraquezas dos fracos. Seja o forte de alguém hoje.'),
  (157, 'Provérbios 27:12', 'O prudente vê o mal e se esconde; mas os insensatos passam adiante e sofrem a pena.', 'prudencia', 'O prudente vê o mal e se esconde. Descanse antes de lesionar.'),
  (158, 'Salmos 34:19', 'Muitas são as aflições do justo, mas de todas elas o Senhor o livra.', 'resiliencia', 'Muitas são as aflições do justo, mas de todas ele é livre.'),
  (159, '1 Pedro 1:6', 'na qual exultais, ainda que agora por um pouco de tempo, sendo necessário, estejais contristados por várias provações,', 'prova', 'Por um pouco de tempo, se necessário, contristados por várias provações.'),
  (160, 'Provérbios 20:11', 'Até a criança se dá a conhecer pelas suas ações, se a sua conduta é pura e reta.', 'identidade', 'Até o menino se conhece pelas suas ações.'),
  (161, 'Salmos 143:10', 'Ensina-me a fazer a tua vontade, pois tu és o meu Deus; guie-me o teu bom Espírito por terreno plano.', 'direcao', 'Ensina-me a fazer a tua vontade. Comece pela do seu corpo.'),
  (162, 'Isaías 40:28', 'Não sabes, não ouviste que o eterno Deus, o Senhor, o Criador dos confins da terra, não se cansa nem se fatiga? E inescrutável o seu entendimento.', 'energia', 'Ele não se cansa nem se fatiga. Empreste um pouco disso hoje.'),
  (163, 'Provérbios 22:6', 'Instrui o menino no caminho em que deve andar, e até quando envelhecer não se desviará dele.', 'habito', 'Instrua o caminho no princípio e ele não se afastará.'),
  (164, 'Salmos 37:7', 'Descansa no Senhor, e espera nele; não te enfades por causa daquele que prospera em seu caminho, por causa do homem que executa maus desígnios.', 'paciencia', 'Descansa e espera. O resultado não some porque demorou.'),
  (165, '2 Pedro 1:5', 'E por isso mesmo vós, empregando toda a diligência, acrescentai à vossa fé a virtude, e à virtude a ciência,', 'crescimento', 'Acrescente à sua fé a virtude, e à virtude o conhecimento.'),
  (166, 'Provérbios 12:11', 'O que lavra a sua terra se fartará de pão; mas o que segue os ociosos é falto de entendimento.', 'trabalho', 'Quem lavra a terra se farta de pão.'),
  (167, 'Salmos 25:4', 'Faze-me saber os teus caminhos, Senhor; ensina-me as tuas veredas.', 'direcao', 'Mostra-me os teus caminhos. Depois ande neles.'),
  (168, 'Mateus 6:33', 'Mas buscai primeiro o seu reino e a sua justiça, e todas estas coisas vos serão acrescentadas.', 'prioridade', 'Busque primeiro o que importa. O resto se ajeita.'),
  (169, 'Provérbios 10:22', 'A bênção do Senhor é que enriquece; e ele não a faz seguir de dor alguma.', 'gratidao', 'A bênção enriquece e não traz consigo tristeza.'),
  (170, 'Salmos 68:35', 'Ó Deus, tu és tremendo desde o teu santuário; o Deus de Israel, ele dá força e poder ao seu povo. Bendito seja Deus!', 'forca', 'Ele dá força e poder ao seu povo.'),
  (171, 'Hebreus 4:16', 'Cheguemo-nos, pois, confiadamente ao trono da graça, para que recebamos misericórdia e achemos graça, a fim de sermos socorridos no momento oportuno.', 'coragem', 'Cheguemos com confiança. Inclusive à barra.'),
  (172, 'Provérbios 14:29', 'Quem é tardio em irar-se é grande em entendimento; mas o que é de ânimo precipitado exalta a loucura.', 'paciencia', 'Quem é tardio em irar-se tem grande entendimento.'),
  (173, 'Salmos 121:3', 'Não deixará vacilar o teu pé; aquele que te guarda não dormitará.', 'seguranca', 'Não deixará vacilar o teu pé.'),
  (174, 'Isaías 41:13', 'Porque eu, o Senhor teu Deus, te seguro pela tua mão direita, e te digo: Não temas; eu te ajudarei.', 'coragem', 'Eu te seguro pela mão direita. Não temas.'),
  (175, 'Provérbios 19:20', 'Ouve o conselho, e recebe a correção, para que sejas sábio nos teus últimos dias.', 'aprendizado', 'Ouça o conselho e aceite a correção para ser sábio no fim.'),
  (176, 'Salmos 119:71', 'Foi-me bom ter sido afligido, para que aprendesse os teus estatutos.', 'prova', 'Foi bom para mim ter sido afligido, para que aprendesse.'),
  (177, '1 Coríntios 16:13', 'Vigiai, estai firmes na fé, portai-vos varonilmente, sede fortes.', 'firmeza', 'Vigiai, estai firmes na fé, portai-vos varonilmente, fortalecei-vos.'),
  (178, 'Provérbios 4:12', 'Quando andares, não se embaraçarão os teus passos; e se correres, não tropeçarás.', 'caminho', 'Quando andares, não se embaraçarão os teus passos.'),
  (179, 'Salmos 3:3', 'Mas tu, Senhor, és um escudo ao redor de mim, a minha glória, e aquele que exulta a minha cabeça.', 'animo', 'Tu és o escudo e o que exalta a minha cabeça.'),
  (180, 'Eclesiastes 5:12', 'Doce é o sono do trabalhador, quer coma pouco quer muito; mas a saciedade do rico não o deixa dormir.', 'sono', 'Doce é o sono do trabalhador.'),
  (181, 'Provérbios 31:25', 'Aine. A força e a dignidade são os seus vestidos; e ri-se do tempo vindouro.', 'futuro', 'A força é o seu vestido e ri-se do dia de amanhã.'),
  (182, 'Salmos 18:29', 'Com o teu auxílio dou numa tropa; com o meu Deus salto uma muralha.', 'superacao', 'Contigo salto muralhas.'),
  (183, 'Filipenses 2:13', 'porque Deus é o que opera em vós tanto o querer como o efetuar, segundo a sua boa vontade.', 'vontade', 'É ele quem produz em vós tanto o querer quanto o realizar.'),
  (184, 'Provérbios 3:24', 'Quando te deitares, não temerás; sim, tu te deitarás e o teu sono será suave.', 'sono', 'Quando te deitares, o teu sono será suave.'),
  (185, 'Salmos 27:1', 'O Senhor é a minha luz e a minha salvação; a quem temerei? O Senhor é a força da minha vida; de quem me recearei?', 'coragem', 'A quem temerei? Nem ao relógio, nem ao espelho.'),
  (186, 'Provérbios 16:24', 'Palavras suaves são como favos de mel, doçura para a alma e saúde para o corpo.', 'palavras', 'Palavras suaves são favo de mel. Fale bem de você hoje.'),
  (187, 'Isaías 12:2', 'Eis que Deus é a minha salvação; eu confiarei e não temerei porque o Senhor, sim o Senhor é a minha força e o meu cântico; e se tornou a minha salvação.', 'confianca', 'Confiarei e não temerei. Ele é a minha força e o meu cântico.'),
  (188, 'Tiago 3:2', 'Pois todos tropeçamos em muitas coisas. Se alguém não tropeça em palavra, esse é homem perfeito, e capaz de refrear também todo o corpo.', 'humildade', 'Todos tropeçamos em muitas coisas. Levante e siga.'),
  (189, 'Salmos 133:1', 'Oh! quão bom e quão suave é que os irmãos vivam em união!', 'comunidade', 'Como é bom os irmãos viverem em união. Chame alguém para treinar.'),
  (190, 'Provérbios 25:16', 'Se achaste mel, come somente o que te basta, para que porventura não te fartes dele, e o venhas a vomitar.', 'equilibrio', 'Achou mel? Coma o suficiente. Vale para tudo, inclusive treino.'),
  (191, 'Romanos 12:11', 'não sejais vagarosos no cuidado; sede fervorosos no espírito, servindo ao Senhor;', 'empenho', 'No zelo, não sejais remissos. Sede fervorosos de espírito.'),
  (192, 'Salmos 16:11', 'Tu me farás conhecer a vereda da vida; na tua presença há plenitude de alegria; à tua mão direita há delícias perpetuamente.', 'alegria', 'Na tua presença há plenitude de alegria.'),
  (193, 'Provérbios 24:27', 'Prepara os teus trabalhos de fora, apronta bem o teu campo; e depois edifica a tua casa.', 'ordem', 'Prepare a obra de fora e depois edifique a casa.'),
  (194, '1 Timóteo 6:12', 'Peleja a boa peleja da fé, apodera-te da vida eterna, para a qual foste chamado, tendo já feito boa confissão diante de muitas testemunhas.', 'luta', 'Milita a boa milícia. Todo dia é um round.'),
  (195, 'Salmos 86:11', 'Louvar-te-ei, Senhor Deus meu, de todo o meu coração, e glorificarei o teu nome para sempre.', 'foco', 'Une o meu coração. Deixe de fazer três coisas ao mesmo tempo.'),
  (196, 'Isaías 45:2', 'eu irei adiante de ti, e tornarei planos os lugares escabrosos; quebrarei as portas de bronze, e despedaçarei os ferrolhos de ferro.', 'caminho', 'Eu irei adiante de ti e endireitarei os caminhos tortuosos.'),
  (197, 'Provérbios 13:20', 'Quem anda com os sábios será sábio; mas o companheiro dos tolos sofre aflição.', 'companhia', 'Quem anda com sábios será sábio. Escolha bem quem te influencia.'),
  (198, 'Salmos 34:5', 'Olhai para ele, e sede iluminados; e os vossos rostos jamais serão confundidos.', 'animo', 'Olharam para ele e foram iluminados. O rosto não ficou envergonhado.'),
  (199, 'Hebreus 13:5', 'Seja a vossa vida isenta de ganância, contentando-vos com o que tendes; porque ele mesmo disse: Não te deixarei, nem te desampararei.', 'contentamento', 'Contentai-vos com o que tendes. Comece com o corpo que tem.'),
  (200, 'Provérbios 18:10', 'Torre forte é o nome do Senhor; para ela corre o justo, e está seguro.', 'seguranca', 'Torre forte. Para lá corre o justo e fica seguro.'),
  (201, 'Salmos 42:8', 'Contudo, de dia o Senhor ordena a sua bondade, e de noite a sua canção está comigo, uma oração ao Deus da minha vida.', 'rotina', 'De dia a bondade, de noite o cântico. Todo dia tem a sua parte.'),
  (202, 'Mateus 19:26', 'Jesus, fixando neles o olhar, respondeu: Aos homens é isso impossível, mas a Deus tudo é possível.', 'possibilidade', 'Aos homens é impossível. Não a você com método.'),
  (203, 'Provérbios 28:20', 'O homem fiel gozará de abundantes bênçãos; mas o que se apressa a enriquecer não ficará impune.', 'constancia', 'O homem fiel terá muitas bênçãos. Quem quer enriquecer depressa não fica sem culpa.'),
  (204, 'Salmos 105:4', 'Buscai ao Senhor e a sua força; buscai a sua face continuamente.', 'forca', 'Buscai o Senhor e a sua força. Buscai a sua face continuamente.'),
  (205, 'Efésios 3:16', 'para que, segundo as riquezas da sua glória, vos conceda que sejais robustecidos com poder pelo seu Espírito no homem interior;', 'interior', 'Fortalecidos com poder no homem interior.'),
  (206, 'Provérbios 5:21', 'Porque os caminhos do homem estão diante dos olhos do Senhor, o qual observa todas as suas veredas.', 'verdade', 'Os caminhos do homem estão diante dos olhos do Senhor.'),
  (207, 'Salmos 51:12', 'Restitui-me a alegria da tua salvação, e sustém-me com um espírito voluntário.', 'alegria', 'Restitui-me a alegria da tua salvação e sustenta-me.'),
  (208, 'Isaías 40:11', 'Como pastor ele apascentará o seu rebanho; entre os seus braços recolherá os cordeirinhos, e os levará no seu regaço; as que amamentam, ele as guiará mansamente.', 'cuidado', 'Ele conduz suavemente as que amamentam. Vá no seu ritmo.'),
  (209, 'Provérbios 15:16', 'Melhor é o pouco com o temor do Senhor, do que um grande tesouro, e com ele a inquietação.', 'simplicidade', 'Melhor o pouco com paz do que muito com inquietação.'),
  (210, 'Salmos 145:18', 'Perto está o Senhor de todos os que o invocam, de todos os que o invocam em verdade.', 'proximidade', 'Perto está de todos os que o invocam.'),
  (211, '2 Timóteo 2:3', 'Sofre comigo como bom soldado de Cristo Jesus.', 'resistencia', 'Sofre as aflições como bom soldado.'),
  (212, 'Provérbios 11:17', 'O homem bondoso faz bem à sua, própria alma; mas o cruel faz mal a si mesmo.', 'cuidado', 'O homem misericordioso faz bem à sua própria alma.'),
  (213, 'Salmos 119:60', 'Apresso-me sem detença a observar os teus mandamentos.', 'prontidao', 'Apressei-me e não me detive a observar os teus mandamentos.'),
  (214, 'Lucas 6:48', 'É semelhante ao homem que, edificando uma casa, cavou, abriu profunda vala, e pôs os alicerces sobre a rocha; e vindo a enchente, bateu com ímpeto a torrente naquela casa, e não a pôde abalar, porque tinha sido bem edificada.', 'fundamento', 'Cavou fundo e pôs o alicerce sobre a rocha.'),
  (215, 'Provérbios 21:21', 'Aquele que segue a justiça e a bondade achará a vida, a justiça e a honra.', 'carater', 'Quem segue a justiça acha a vida.'),
  (216, 'Salmos 37:24', 'ainda que caia, não ficará prostrado, pois o Senhor lhe segura a mão.', 'recomeco', 'Ainda que caia, não ficará prostrado.'),
  (217, 'Isaías 46:4', 'Até a vossa velhice eu sou o mesmo, e ainda até as cãs eu vos carregarei; eu vos criei, e vos levarei; sim, eu vos carregarei e vos livrarei.', 'longevidade', 'Até a velhice eu serei o mesmo. Eu vos levarei.'),
  (218, 'Provérbios 12:25', 'A ansiedade no coração do homem o abate; mas uma boa palavra o alegra.', 'animo', 'A ansiedade abate. A boa palavra alegra.'),
  (219, 'Salmos 40:8', 'Deleito-me em fazer a tua vontade, ó Deus meu; sim, a tua lei está dentro do meu coração.', 'vontade', 'Deleito-me em fazer a tua vontade. Ache prazer no que você escolheu.'),
  (220, 'Hebreus 12:2', 'fitando os olhos em Jesus, autor e consumador da nossa fé, o qual, pelo gozo que lhe está proposto, suportou a cruz, desprezando a ignomínia, e está assentado à direita do trono de Deus.', 'foco', 'Olhando para o alvo. Não para o cansaço.'),
  (221, 'Provérbios 22:4', 'O galardão da humildade e do temor do Senhor é riquezas, e honra e vida.', 'humildade', 'O galardão da humildade e do temor é riqueza, honra e vida.'),
  (222, 'Salmos 4:8', 'Em paz me deitarei e dormirei, porque só tu, Senhor, me fazes habitar em segurança.', 'descanso', 'Em paz me deitarei e dormirei.'),
  (223, '1 João 4:18', 'No amor não há medo antes o perfeito amor lança fora o medo; porque o medo envolve castigo; e quem tem medo não está aperfeiçoado no amor.', 'coragem', 'O perfeito amor lança fora o medo.'),
  (224, 'Provérbios 17:17', 'O amigo ama em todo o tempo; e para a angústia nasce o irmão.', 'amizade', 'Em todo tempo ama o amigo, e na angústia nasce o irmão.'),
  (225, 'Salmos 23:3', 'Refrigera a minha alma; guia-me nas veredas da justiça por amor do seu nome.', 'renovacao', 'Refrigera a minha alma. Guia-me pelas veredas da justiça.'),
  (226, 'Isaías 32:17', 'E a obra da justiça será paz; e o efeito da justiça será sossego e segurança para sempre.', 'paz', 'O efeito da justiça será paz, e a operação da justiça, segurança.'),
  (227, 'Provérbios 14:15', 'O simples dá crédito a tudo; mas o prudente atenta para os seus passos.', 'prudencia', 'O prudente atenta para os seus passos.'),
  (228, 'Salmos 71:14', 'Mas eu esperarei continuamente, e te louvarei cada vez mais.', 'esperanca', 'Mas eu esperarei continuamente e te louvarei ainda mais.'),
  (229, 'Romanos 4:20', 'contudo, à vista da promessa de Deus, não vacilou por incredulidade, antes foi fortalecido na fé, dando glória a Deus,', 'fe', 'Não duvidou por incredulidade, mas foi fortificado na fé.'),
  (230, 'Provérbios 3:6', 'Reconhece-o em todos os teus caminhos, e ele endireitará as tuas veredas.', 'direcao', 'Reconhece-o em todos os teus caminhos e ele endireitará as tuas veredas.'),
  (231, 'Salmos 62:5', 'Ó minha alma, espera silenciosa somente em Deus, porque dele vem a minha esperança.', 'paciencia', 'Espera somente em Deus, ó minha alma.'),
  (232, 'Eclesiastes 9:11', 'Observei ainda e vi que debaixo do sol não é dos ligeiros a carreira, nem dos fortes a peleja, nem tampouco dos sábios o pão, nem ainda dos prudentes a riqueza, nem dos entendidos o favor; mas que a ocasião e a sorte ocorrem a todos.', 'constancia', 'A corrida não é dos ligeiros. É de quem chega.'),
  (233, 'Provérbios 27:23', 'Procura conhecer o estado das tuas ovelhas; cuida bem dos teus rebanhos;', 'atencao', 'Procura conhecer o estado das tuas ovelhas. Conheça o seu corpo.'),
  (234, 'Salmos 29:11', 'O Senhor dará força ao seu povo; o Senhor abençoará o seu povo com paz.', 'forca', 'O Senhor dará força ao seu povo. O Senhor abençoará com paz.'),
  (235, 'Mateus 7:7', 'Pedí, e dar-se-vos-á; buscai, e achareis; batei e abrir-se-vos-á.', 'insistencia', 'Pedi, buscai, batei. Três verbos, nenhum passivo.'),
  (236, 'Provérbios 20:24', 'Os passos do homem são dirigidos pelo Senhor; como, pois, poderá o homem entender o seu caminho?', 'confianca', 'Os passos do homem são dirigidos pelo Senhor.'),
  (237, 'Salmos 46:10', 'Aquietai-vos, e sabei que eu sou Deus; sou exaltado entre as nações, sou exaltado na terra.', 'calma', 'Aquietai-vos e sabei. Descansar também é treino.'),
  (238, 'Isaías 49:4', 'Mas eu disse: Debalde tenho trabalhado, inútil e vãmente gastei as minhas forças; todavia o meu direito está perante o Senhor, e o meu galardão perante o meu Deus.', 'constancia', 'Ainda que eu ache que trabalhei em vão, o meu direito está com Deus.'),
  (239, 'Provérbios 4:18', 'Mas a vereda dos justos é como a luz da aurora que vai brilhando mais e mais até ser dia perfeito.', 'progresso', 'A vereda dos justos é como a luz da aurora, que vai clareando.'),
  (240, 'Salmos 126:5', 'Os que semeiam em lágrimas, com cânticos de júbilo segarão.', 'colheita', 'Os que semeiam em lágrimas segarão com alegria.'),
  (241, '1 Coríntios 3:8', 'Ora, uma só coisa é o que planta e o que rega; e cada um receberá o seu galardão segundo o seu trabalho.', 'recompensa', 'Cada um receberá conforme o seu próprio trabalho.'),
  (242, 'Provérbios 16:20', 'O que atenta prudentemente para a palavra prosperará; e feliz é aquele que confia no Senhor.', 'sabedoria', 'Quem confia no Senhor é bem-aventurado.'),
  (243, 'Salmos 33:20', 'A nossa alma espera no Senhor; ele é o nosso auxílio e o nosso escudo.', 'espera', 'A nossa alma espera. Ele é o nosso auxílio e o nosso escudo.'),
  (244, 'Hebreus 10:23', 'retenhamos inabalável a confissão da nossa esperança, porque fiel é aquele que fez a promessa;', 'firmeza', 'Retenhamos firmes a confissão da nossa esperança.'),
  (245, 'Provérbios 12:14', 'Do fruto das suas palavras o homem se farta de bem; e das obras das suas mãos se lhe retribui.', 'recompensa', 'A obra das mãos do homem lhe será recompensada.'),
  (246, 'Salmos 94:19', 'Quando os cuidados do meu coração se multiplicam, as tuas consolações recreiam a minha alma.', 'consolo', 'Na multidão dos meus pensamentos, as tuas consolações alegraram a minha alma.'),
  (247, 'Isaías 33:2', 'ç Senhor, tem misericórdia de nós; por ti temos esperado. Sê tu o nosso braço cada manhã, como também a nossa salvação no tempo da tribulação.', 'manha', 'Sê o nosso braço cada manhã.'),
  (248, 'Provérbios 10:9', 'Quem anda em integridade anda seguro; mas o que perverte os seus caminhos será conhecido.', 'integridade', 'Quem anda em sinceridade anda seguro.'),
  (249, 'Salmos 91:11', 'Porque aos seus anjos dará ordem a teu respeito, para te guardarem em todos os teus caminhos.', 'protecao', 'Ele dará ordens a seus anjos a teu respeito.'),
  (250, 'Tiago 1:4', 'e a perseverança tenha a sua obra perfeita, para que sejais perfeitos e completos, não faltando em coisa alguma.', 'paciencia', 'Que a paciência tenha a sua obra perfeita.'),
  (251, 'Provérbios 23:18', 'Porque deveras terás uma recompensa; não será malograda a tua esperança.', 'esperanca', 'Certamente há um futuro, e a tua esperança não será cortada.'),
  (252, 'Salmos 138:8', 'O Senhor aperfeiçoará o que me diz respeito. A tua benignidade, ó Senhor, dura para sempre; não abandones as obras das tuas mãos.', 'confianca', 'O Senhor aperfeiçoará o que me diz respeito.'),
  (253, 'Marcos 11:24', 'Por isso vos digo que tudo o que pedirdes em oração, crede que o recebereis, e tê-lo-eis.', 'fe', 'Tudo o que pedirdes, crede que o recebereis.'),
  (254, 'Provérbios 15:23', 'O homem alegra-se em dar uma resposta adequada; e a palavra a seu tempo quão boa é!', 'palavras', 'Como é boa a palavra a seu tempo.'),
  (255, 'Salmos 130:5', 'Aguardo ao Senhor; a minha alma o aguarda, e espero na sua palavra.', 'espera', 'Aguardo o Senhor. A minha alma o aguarda.'),
  (256, 'Isaías 26:4', 'Confiai sempre no Senhor; porque o Senhor Deus é uma rocha eterna.', 'confianca', 'Confiai no Senhor perpetuamente, porque nele há uma rocha eterna.'),
  (257, 'Provérbios 24:5', 'O sábio é mais poderoso do que o forte; e o inteligente do que o que possui a força.', 'forca', 'O homem sábio é forte, e o de conhecimento consolida a força.'),
  (258, 'Salmos 37:4', 'Deleita-te também no Senhor, e ele te concederá o que deseja o teu coração.', 'alegria', 'Deleita-te no Senhor e ele te concederá os desejos do teu coração.'),
  (259, 'Filipenses 4:8', 'Quanto ao mais, irmãos, tudo o que é verdadeiro, tudo o que é honesto, tudo o que é justo, tudo o que é puro, tudo o que é amável, tudo o que é de boa fama, se há alguma virtude, e se há algum louvor, nisso pensai.', 'pensamento', 'Tudo o que é verdadeiro e honesto, nisso pensai.'),
  (260, 'Provérbios 6:9', 'o preguiçoso, até quando ficarás deitador? quando te levantarás do teu sono?', 'acao', 'Até quando ficarás deitado? Quando te levantarás?'),
  (261, 'Salmos 57:7', 'Resoluto está o meu coração, ó Deus, resoluto está o meu coração; cantarei, sim, cantarei louvores.', 'firmeza', 'Preparado está o meu coração. Cantarei e darei louvores.'),
  (262, '1 Pedro 5:10', 'E o Deus de toda a graça, que em Cristo vos chamou à sua eterna glória, depois de haverdes sofrido por um pouco, ele mesmo vos há de aperfeiçoar, confirmar e fortalecer.', 'restauracao', 'Depois de terdes padecido um pouco, ele mesmo vos aperfeiçoará.'),
  (263, 'Provérbios 8:17', 'Eu amo aos que me amam, e os que diligentemente me buscam me acharão.', 'busca', 'Os que cedo me buscarem me acharão.'),
  (264, 'Salmos 119:165', 'Muita paz têm os que amam a tua lei, e não há nada que os faça tropeçar.', 'paz', 'Muita paz têm os que amam a tua lei, e para eles não há tropeço.'),
  (265, 'Isaías 25:1', 'ç Senhor, tu és o meu Deus; exaltarte-ei a ti, e louvarei o teu nome; porque fizeste maravilhas, os teus conselhos antigos, em fidelidade e em verdade.', 'gratidao', 'Tu fizeste maravilhas. Os teus conselhos antigos são fiéis e verdadeiros.'),
  (266, 'Provérbios 29:25', 'O receio do homem lhe arma laços; mas o que confia no Senhor está seguro.', 'coragem', 'O temor do homem armará laços. Quem confia no Senhor estará seguro.'),
  (267, 'Salmos 84:5', 'Bem-aventurados os homens cuja força está em ti, em cujo coração os caminhos altos.', 'caminho', 'Bem-aventurado o homem cuja força está em ti, em cujo coração estão os caminhos.'),
  (268, 'Romanos 8:28', 'E sabemos que todas as coisas concorrem para o bem daqueles que amam a Deus, daqueles que são chamados segundo o seu propósito.', 'proposito', 'Todas as coisas contribuem juntamente para o bem.'),
  (269, 'Provérbios 13:12', 'A esperança adiada entristece o coração; mas o desejo cumprido é árvore devida.', 'esperanca', 'A esperança adiada adoece o coração, mas o desejo cumprido é árvore de vida.'),
  (270, 'Salmos 42:1', 'Como o cervo anseia pelas correntes das águas, assim a minha alma anseia por ti, ó Deus!', 'sede', 'Como o cervo brama pelas correntes das águas.'),
  (271, 'Hebreus 11:6', 'Ora, sem fé é impossível agradar a Deus; porque é necessário que aquele que se aproxima de Deus creia que ele existe, e que é galardoador dos que o buscam.', 'fe', 'É galardoador dos que diligentemente o buscam.'),
  (272, 'Provérbios 21:23', 'O que guarda a sua boca e a sua língua, guarda das angústias a sua alma.', 'dominio', 'Quem guarda a boca e a língua guarda a sua alma das angústias.'),
  (273, 'Salmos 19:14', 'Sejam agradáveis as palavras da minha boca e a meditação do meu coração perante a tua face, Senhor, Rocha minha e Redentor meu!', 'intencao', 'Sejam agradáveis as palavras da minha boca e a meditação do meu coração.'),
  (274, 'Isaías 64:8', 'Mas agora, ó Senhor, tu és nosso Pai; nós somos o barro, e tu o nosso oleiro; e todos nós obra das tuas mãos.', 'processo', 'Nós somos o barro e tu és o nosso oleiro.'),
  (275, 'Provérbios 1:5', 'Ouça também, o sábio e cresça em ciência, e o entendido adquira habilidade,', 'aprendizado', 'O sábio ouvirá e crescerá em conhecimento.'),
  (276, 'Salmos 118:14', 'O Senhor é a minha força e o meu cântico; tornou-se a minha salvação.', 'forca', 'O Senhor é a minha força e o meu cântico.'),
  (277, 'Provérbios 14:1', 'Toda mulher sábia edifica a sua casa; a insensata, porém, derruba-a com as suas mãos.', 'construcao', 'A mulher sábia edifica a sua casa. Você edifica o seu corpo.'),
  (278, 'Isaías 52:2', 'Sacode-te do pó; levanta-te, e assenta-te, ó Jerusalém; solta-te das ataduras de teu pescoço, ó cativa filha de Sião.', 'recomeco', 'Sacode o pó, levanta-te e assenta-te.'),
  (279, 'Tiago 4:8', 'Chegai-vos para Deus, e ele se chegará para vós. Limpai as mãos, pecadores; e, vós de espírito vacilante, purificai os corações.', 'proximidade', 'Chegai-vos a Deus e ele se chegará a vós.'),
  (280, 'Salmos 107:9', 'Pois ele satisfaz a alma sedenta, e enche de bens a alma faminta.', 'satisfacao', 'Ele fartou a alma sedenta e encheu de bens a alma faminta.'),
  (281, 'Provérbios 28:19', 'O que lavra a sua terra se fartará de pão; mas o que segue os ociosos se encherá de pobreza.', 'trabalho', 'Quem lavra a sua terra se fartará de pão.'),
  (282, '1 Coríntios 13:7', 'tudo sofre, tudo crê, tudo espera, tudo suporta.', 'perseveranca', 'Tudo sofre, tudo crê, tudo espera, tudo suporta.'),
  (283, 'Salmos 65:11', 'Coroas o ano com a tua bondade, e as tuas veredas destilam gordura;', 'gratidao', 'Coroas o ano com a tua bondade.'),
  (284, 'Provérbios 11:18', 'O ímpio recebe um salário ilusório; mas o que semeia justiça recebe galardão seguro.', 'semeadura', 'Quem semeia justiça terá recompensa segura.'),
  (285, 'Isaías 43:18', 'Não vos lembreis das coisas passadas, nem considereis as antigas.', 'recomeco', 'Não vos lembreis das coisas passadas. Eis que faço uma coisa nova.'),
  (286, 'Salmos 5:12', 'Pois tu, Senhor, abençoas o justo; tu o circundas do teu favor como de um escudo.', 'protecao', 'Tu, Senhor, abençoarás ao justo. Com benevolência o cercarás como de um escudo.'),
  (287, 'Mateus 5:16', 'Assim resplandeça a vossa luz diante dos homens, para que vejam as vossas boas obras, e glorifiquem a vosso Pai, que está nos céus.', 'exemplo', 'Assim resplandeça a vossa luz. Alguém está olhando a sua constância.'),
  (288, 'Provérbios 3:3', 'Não se afastem de ti a benignidade e a fidelidade; ata-as ao teu pescoço, escreve-as na tábua do teu coração;', 'carater', 'Não te desamparem a benignidade e a fidelidade.'),
  (289, 'Salmos 25:15', 'Os meus olhos estão postos continuamente no Senhor, pois ele tirará do laço os meus pés.', 'foco', 'Os meus olhos estão continuamente no Senhor.'),
  (290, 'Hebreus 3:13', 'antes exortai-vos uns aos outros todos os dias, durante o tempo que se chama Hoje, para que nenhum de vós se endureça pelo engano do pecado;', 'comunidade', 'Exortai-vos uns aos outros todos os dias.'),
  (291, 'Provérbios 19:8', 'O que adquire a sabedoria é amigo de si mesmo; o que guarda o entendimento prosperará.', 'cuidado', 'Quem adquire entendimento ama a sua alma.'),
  (292, 'Salmos 34:18', 'Perto está o Senhor dos que têm o coração quebrantado, e salva os contritos de espírito.', 'consolo', 'Perto está o Senhor dos que têm o coração quebrantado.'),
  (293, 'Isaías 40:26', 'Levantai ao alto os vossos olhos, e vede: quem criou estas coisas? Foi aquele que faz sair o exército delas segundo o seu número; ele as chama a todas pelos seus nomes; por ser ele grande em força, e forte em poder, nenhuma faltará.', 'grandeza', 'Levantai ao alto os vossos olhos e vede quem criou estas coisas.'),
  (294, 'Provérbios 16:1', 'Ao homem pertencem os planos do coração; mas a resposta da língua é do Senhor.', 'planejamento', 'Do homem são os planos do coração, mas do Senhor a resposta.'),
  (295, 'Salmos 103:2', 'Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum dos seus benefícios.', 'gratidao', 'Bendize, ó minha alma, e não te esqueças de nenhum dos seus benefícios.'),
  (296, '2 Coríntios 5:7', '(porque andamos por fé, e não por vista);', 'fe', 'Andamos por fé e não por vista.'),
  (297, 'Provérbios 25:11', 'Como maçãs de ouro em salvas de prata, assim é a palavra dita a seu tempo.', 'palavras', 'Como maçãs de ouro em salvas de prata é a palavra dita a seu tempo.'),
  (298, 'Salmos 32:7', 'Tu és o meu esconderijo; preservas-me da angústia; de alegres cânticos de livramento me cercas.', 'abrigo', 'Tu és o lugar em que me escondo. Tu me preservas da angústia.'),
  (299, 'Isaías 30:21', 'e os teus ouvidos ouvirão a palavra do que está por detrás de ti, dizendo: Este é o caminho, andai nele; quando vos desviardes para a direita ou para a esquerda.', 'direcao', 'Este é o caminho, andai por ele.'),
  (300, 'Provérbios 22:3', 'O prudente vê o perigo e esconde-se; mas os simples passam adiante e sofrem a pena.', 'prudencia', 'O prudente vê o mal e esconde-se. O simples passa e sofre a pena.'),
  (301, 'Salmos 40:5', 'Muitas são, Senhor, Deus meu, as maravilhas que tens operado e os teus pensamentos para conosco; ninguém há que se possa comparar a ti; eu quisera anunciá-los, e manifestá-los, mas são mais do que se podem contar.', 'gratidao', 'Muitas são as maravilhas que tens feito. Não se podem contar.'),
  (302, 'Filipenses 4:11', 'Não digo isto por causa de necessidade, porque já aprendi a contentar-me com as circunstâncias em que me encontre.', 'contentamento', 'Aprendi a contentar-me com o que tenho.'),
  (303, 'Provérbios 12:15', 'O caminho do insensato é reto aos seus olhos; mas o que dá ouvidos ao conselho é sábio.', 'humildade', 'O caminho do tolo é reto aos seus olhos, mas o sábio ouve conselhos.'),
  (304, 'Salmos 143:5', 'Lembro-me dos dias antigos; considero todos os teus feitos; medito na obra das tuas mãos.', 'memoria', 'Lembro-me dos dias antigos. Medito em todos os teus feitos.'),
  (305, 'Lucas 12:25', 'Ora, qual de vós, por mais ansioso que esteja, pode acrescentar um côvado à sua estatura?', 'ansiedade', 'Quem de vós, cuidando, pode acrescentar um côvado à sua estatura?'),
  (306, 'Provérbios 15:33', 'O temor do Senhor é a instrução da sabedoria; e adiante da honra vai a humildade.', 'humildade', 'Antes da honra vai a humildade.'),
  (307, 'Salmos 121:8', 'O Senhor guardará a tua saída e a tua entrada, desde agora e para sempre.', 'protecao', 'O Senhor guardará a tua saída e a tua entrada.'),
  (308, 'Habacuque 3:19', 'O Senhor Deus é minha força, ele fará os meus pés como os da corça, e me fará andar sobre os meus lugares altos. (Ao regente de música. Para instrumentos de cordas.)', 'resistencia', 'Ele faz os meus pés como os das cervas. Confie no que o corpo aprendeu.'),
  (309, 'Provérbios 4:26', 'Pondera a vereda de teus pés, e serão seguros todos os teus caminhos.', 'atencao', 'Pondera a vereda dos teus pés e todos os teus caminhos sejam bem ordenados.'),
  (310, 'Salmos 37:34', 'Espera no Senhor, e segue o seu caminho, e ele te exaltará para herdares a terra; tu o verás quando os ímpios forem exterminados.', 'espera', 'Espera no Senhor e guarda o seu caminho.'),
  (311, '1 Timóteo 4:15', 'Ocupa-te destas coisas, dedica-te inteiramente a elas, para que o teu progresso seja manifesto a todos.', 'progresso', 'Ocupa-te destas coisas para que o teu progresso seja manifesto a todos.'),
  (312, 'Provérbios 9:10', 'O temor do Senhor é o princípio sabedoria; e o conhecimento do Santo é o entendimento.', 'sabedoria', 'O temor do Senhor é o princípio da sabedoria.'),
  (313, 'Salmos 63:7', 'pois tu tens sido o meu auxílio; de júbilo canto à sombra das tuas asas.', 'gratidao', 'À sombra das tuas asas me regozijo.'),
  (314, 'Isaías 55:6', 'Buscai ao Senhor enquanto se pode achar, invocai-o enquanto está perto.', 'urgencia', 'Buscai o Senhor enquanto se pode achar.'),
  (315, 'Provérbios 20:13', 'Não ames o sono, para que não empobreças; abre os teus olhos, e te fartarás de pão.', 'acao', 'Não ames o sono, para que não empobreças.'),
  (316, 'Salmos 92:1', 'Bom é render graças ao Senhor, e cantar louvores ao teu nome, ó Altíssimo,', 'gratidao', 'Bom é louvar ao Senhor e cantar louvores ao teu nome.'),
  (317, 'Romanos 13:11', 'E isso fazei, conhecendo o tempo, que já é hora de despertardes do sono; porque a nossa salvação está agora mais perto de nós do que quando nos tornamos crentes.', 'urgencia', 'É já hora de despertarmos do sono.'),
  (318, 'Provérbios 27:19', 'Como na água o rosto corresponde ao rosto, assim o coração do homem ao homem.', 'identidade', 'Como na água o rosto corresponde ao rosto, assim o coração do homem ao homem.'),
  (319, 'Salmos 145:9', 'O Senhor é bom para todos, e as suas misericórdias estão sobre todas as suas obras.', 'bondade', 'O Senhor é bom para todos, e as suas misericórdias são sobre todas as suas obras.'),
  (320, 'Isaías 44:3', 'Porque derramarei água sobre o sedento, e correntes sobre a terra seca; derramarei o meu Espírito sobre a tua posteridade, e a minha bênção sobre a tua descendência;', 'renovacao', 'Derramarei água sobre o sedento e rios sobre a terra seca.'),
  (321, 'Provérbios 14:22', 'Porventura não erram os que maquinam o mal? mas há beneficência e fidelidade para os que planejam o bem.', 'carater', 'Benignidade e fidelidade serão para os que planejam o bem.'),
  (322, 'Salmos 27:13', 'Creio que hei de ver a bondade do Senhor na terra dos viventes.', 'esperanca', 'Eu creria que veria os bens do Senhor na terra dos viventes.'),
  (323, 'Hebreus 13:21', 'vos aperfeiçoe em toda boa obra, para fazerdes a sua vontade, operando em nós o que perante ele é agradável, por meio de Jesus Cristo, ao qual seja glória para todo o sempre. Amém.', 'capacitacao', 'Vos aperfeiçoe em toda a boa obra, para fazerdes a sua vontade.'),
  (324, 'Provérbios 18:15', 'O coração do entendido adquire conhecimento; e o ouvido dos sábios busca conhecimento;', 'aprendizado', 'O coração do entendido adquire conhecimento.'),
  (325, 'Salmos 31:3', 'Porque tu és a minha rocha e a minha fortaleza; pelo que, por amor do teu nome, guia-me e encaminha-me.', 'direcao', 'Por amor do teu nome, guia-me e encaminha-me.'),
  (326, 'Isaías 61:1', 'O Espírito do Senhor Deus está sobre mim, porque o Senhor me ungiu para pregar boas-novas aos mansos; enviou-me a restaurar os contritos de coração, a proclamar liberdade aos cativos, e a abertura de prisão aos presos;', 'liberdade', 'Enviou-me a apregoar liberdade aos cativos.'),
  (327, 'Provérbios 13:16', 'Em tudo o homem prudente procede com conhecimento; mas o tolo espraia a sua insensatez.', 'prudencia', 'Todo prudente procede com conhecimento.'),
  (328, 'Salmos 119:11', 'Escondi a tua palavra no meu coração, para não pecar contra ti.', 'memoria', 'Escondi a tua palavra no meu coração.'),
  (329, 'Mateus 9:29', 'Então lhes tocou os olhos, dizendo: Seja-vos feito segundo a vossa fé.', 'fe', 'Seja-vos feito segundo a vossa fé.'),
  (330, 'Provérbios 23:4', 'Não te fatigues para seres rico; dá de mão à tua própria sabedoria:', 'equilibrio', 'Não te fatigues para enriqueceres. Usa a tua prudência.'),
  (331, 'Salmos 16:5', 'Tu, Senhor, és a porção da minha herança e do meu cálice; tu és o sustentáculo do meu quinhão.', 'contentamento', 'O Senhor é a porção da minha herança e do meu cálice.'),
  (332, 'Isaías 58:8', 'Então romperá a tua luz como a alva, e a tua cura apressadamente brotará. e a tua justiça irá adiante de ti; e a glória do Senhor será a tua retaguarda.', 'cura', 'A tua cura apressará. A tua justiça irá adiante de ti.'),
  (333, 'Provérbios 21:5', 'Os planos do diligente conduzem à abundância; mas todo precipitado apressa-se para a penúria.', 'planejamento', 'Os planos do diligente tendem à abundância.'),
  (334, 'Salmos 111:10', 'O temor do Senhor é o princípio da sabedoria; têm bom entendimento todos os que cumprem os seus preceitos; o seu louvor subsiste para sempre.', 'sabedoria', 'O temor do Senhor é o princípio da sabedoria. Bom entendimento têm os que o praticam.'),
  (335, '2 Tessalonicenses 3:13', 'Vós, porém, irmãos, não vos canseis de fazer o bem.', 'constancia', 'Não vos canseis de fazer o bem.'),
  (336, 'Provérbios 30:5', 'Toda palavra de Deus é pura; ele é um escudo para os que nele confiam.', 'confianca', 'Ele é o escudo para os que confiam nele.'),
  (337, 'Salmos 56:3', 'No dia em que eu temer, hei de confiar em ti.', 'coragem', 'No dia em que eu temer, hei de confiar em ti.'),
  (338, 'Isaías 35:6', 'Então o coxo saltará como o cervo, e a língua do mudo cantará de alegria; porque águas arrebentarão no deserto e ribeiros no ermo.', 'movimento', 'Então o coxo saltará como o cervo.'),
  (339, 'Provérbios 17:27', 'Refreia as suas palavras aquele que possui o conhecimento; e o homem de entendimento é de espírito sereno.', 'dominio', 'Quem retém as suas palavras tem conhecimento. O homem de entendimento é de espírito sereno.'),
  (340, 'Salmos 108:13', 'Em Deus faremos proezas; porque é ele quem calcará aos pés os nossos inimigos.', 'vitoria', 'Em Deus faremos proezas.'),
  (341, 'Efésios 2:10', 'Porque somos feitura sua, criados em Cristo Jesus para boas obras, as quais Deus antes preparou para que andássemos nelas.', 'proposito', 'Somos feitura sua, criados para boas obras.'),
  (342, 'Provérbios 24:14', 'Sabe que é assim a sabedoria para a tua alma: se a achares, haverá para ti recompensa, e não será malograda a tua esperança.', 'esperanca', 'Achando a sabedoria, haverá para ti galardão, e a tua esperança não será cortada.'),
  (343, 'Salmos 18:2', 'O Senhor é a minha rocha, a minha fortaleza e o meu libertador; o meu Deus, o meu rochedo, em quem me refúgio; o meu escudo, a força da minha salvação, e o meu alto refúgio.', 'seguranca', 'O Senhor é o meu rochedo, a minha fortaleza e o meu libertador.'),
  (344, 'Isaías 60:1', 'Levanta-te, resplandece, porque é chegada a tua luz, e é nascida sobre ti a glória do Senhor.', 'recomeco', 'Levanta-te, resplandece, porque vem a tua luz.'),
  (345, 'Provérbios 11:14', 'Quando não há sábia direção, o povo cai; mas na multidão de conselheiros há segurança.', 'conselho', 'Na multidão de conselheiros há segurança.'),
  (346, 'Salmos 66:9', 'ao que nos conserva em vida, e não consente que resvalem os nossos pés.', 'firmeza', 'É ele quem sustenta a nossa alma em vida e não permite que vacilem os nossos pés.'),
  (347, 'Colossenses 3:17', 'E tudo quanto fizerdes por palavras ou por obras, fazei-o em nome do Senhor Jesus, dando por ele graças a Deus Pai.', 'proposito', 'Tudo quanto fizerdes, por palavras ou por obras, fazei tudo em nome do Senhor.'),
  (348, 'Provérbios 3:9', 'Honra ao Senhor com os teus bens, e com as primícias de toda a tua renda;', 'gratidao', 'Honra ao Senhor com os teus bens e com as primícias de toda a tua renda.'),
  (349, 'Salmos 90:17', 'Seja sobre nós a graça do Senhor, nosso Deus; e confirma sobre nós a obra das nossas mãos; sim, confirma a obra das nossas mãos.', 'confirmacao', 'Confirma sobre nós a obra das nossas mãos.'),
  (350, 'Isaías 26:12', 'Senhor, tu hás de estabelecer para nós a paz; pois tu fizeste para nós todas as nossas obras.', 'paz', 'Senhor, tu nos darás a paz, porque tu fizeste em nós todas as nossas obras.'),
  (351, 'Provérbios 15:13', 'O coração alegre aformoseia o rosto; mas pela dor do coração o espírito se abate.', 'animo', 'O coração alegre aformoseia o rosto.'),
  (352, 'Salmos 34:1', 'Bendirei ao Senhor em todo o tempo; o seu louvor estará continuamente na minha boca.', 'gratidao', 'Louvarei ao Senhor em todo o tempo. O seu louvor estará continuamente na minha boca.'),
  (353, '1 Crônicas 28:20', 'Disse, pois, Davi a seu filho Salomão: Esforça-te e tem bom ânimo, e faze a obra; não temas, nem te desalentes, pois o Senhor Deus, meu Deus, é contigo; não te deixará, nem te desamparará, até que seja acabada toda a obra para o serviço da casa do Senhor.', 'coragem', 'Esforça-te, tem bom ânimo e faze a obra. Não temas nem te apavores.'),
  (354, 'Provérbios 12:27', 'O preguiçoso não apanha a sua caça; mas o bem precioso do homem é para o diligente.', 'diligencia', 'Os bens preciosos do homem são para o diligente.'),
  (355, 'Salmos 147:5', 'Grande é o nosso Senhor, e de grande poder; não há limite ao seu entendimento.', 'grandeza', 'Grande é o nosso Senhor e de grande poder. O seu entendimento é infinito.'),
  (356, 'Isaías 42:16', 'E guiarei os cegos por um caminho que não conhecem; fá-los- ei caminhar por veredas que não têm conhecido; tornarei as trevas em luz perante eles, e aplanados os caminhos escabrosos. Estas coisas lhes farei; e não os desampararei.', 'direcao', 'Guiarei os cegos por um caminho que não conhecem.'),
  (357, 'Provérbios 16:7', 'Quando os caminhos do homem agradam ao Senhor, faz que até os seus inimigos tenham paz com ele.', 'paz', 'Quando os caminhos do homem agradam ao Senhor, ele faz que até os seus inimigos tenham paz com ele.'),
  (358, 'Salmos 116:7', 'Volta, minha alma, ao teu repouso, pois o Senhor te fez bem.', 'descanso', 'Volta, minha alma, ao teu repouso, pois o Senhor te fez bem.'),
  (359, 'Gálatas 6:7', 'Não vos enganeis; Deus não se deixa escarnecer; pois tudo o que o homem semear, isso também ceifará.', 'colheita', 'O que o homem semear, isso também ceifará.'),
  (360, 'Provérbios 28:26', 'O que confia no seu próprio coração é insensato; mas o que anda sabiamente será livre.', 'humildade', 'Quem confia no seu próprio coração é insensato, mas o que anda em sabedoria será salvo.'),
  (361, 'Salmos 139:23', 'Sonda-me, ó Deus, e conhece o meu coração; prova-me, e conhece os meus pensamentos;', 'verdade', 'Sonda-me e conhece o meu coração.'),
  (362, 'Isaías 40:8', 'Seca-se a erva, e murcha a flor; mas a palavra de nosso Deus subsiste eternamente.', 'permanencia', 'A erva seca e a flor cai, mas a palavra do nosso Deus subsiste eternamente.'),
  (363, 'Provérbios 10:28', 'A esperança dos justos é alegria; mas a expectação dos ímpios perecerá.', 'esperanca', 'A esperança dos justos é alegria.'),
  (364, 'Salmos 100:5', 'Porque o Senhor é bom; a sua benignidade dura para sempre, e a sua fidelidade de geração em geração.', 'fidelidade', 'A sua verdade dura de geração em geração.'),
  (365, 'Apocalipse 3:11', 'Venho sem demora; guarda o que tens, para que ninguém tome a tua coroa.', 'firmeza', 'Conserva o que tens, para que ninguém tome a tua coroa.'),
  (366, 'Salmos 150:6', 'Tudo quanto tem fôlego louve ao Senhor. Louvai ao Senhor!', 'gratidao', 'Tudo o que respira, louve. Você respirou hoje: ainda dá tempo.')
on conflict (day_of_year) do update
  set reference = excluded.reference,
      verse = excluded.verse,
      theme = excluded.theme,
      message = excluded.message;
